return {
  {
    'xiyaowong/transparent.nvim',
    lazy = false,
    opts = {
      groups = {
        'Normal',
        'NormalNC',
        'Comment',
        'Constant',
        'Special',
        'Identifier',
        'Statement',
        'PreProc',
        'Type',
        'Underlined',
        'Todo',
        'String',
        'Function',
        'Conditional',
        'Repeat',
        'Operator',
        'Structure',
        'LineNr',
        'NonText',
        'SignColumn',
        'CursorLine',
        'CursorLineNr',
        'StatusLine',
        'StatusLineNC',
        'EndOfBuffer',
      },

      extra_groups = {
        'Pmenu',
        'PmenuSel',
        'PmenuBorder',
        'NormalFloat',
        'FloatBorder',
        'CmpDocumentation',
        'CmpDocumentationBorder',
      },

      exclude_groups = {
        'CursorLine',
        'CursorLineNr',
        'NeoTreeCursorLine',
        'NeoTreeNormal',
        'NeoTreeNormalNC',
        'NeoTreeEndOfBuffer',
        'Pmenu',
        'PmenuSel',
        'PmenuBorder',
        'NormalFloat',
        'FloatBorder',
        'CmpDocumentation',
        'CmpDocumentationBorder',
      },
    },
  },
}
